// Generated by CoffeeScript 1.3.3
(function() {
  var ITunesLib, fs, ituneslib, _;

  _ = require('underscore');

  fs = require('fs');

  module.exports = ituneslib = function(options) {
    var itunesLib;
    if (options == null) {
      options = {};
    }
    return itunesLib = module.exports.instance = new ITunesLib(options);
  };

  ITunesLib = (function() {

    function ITunesLib(options) {
      this.options = options;
    }

    return ITunesLib;

  })();

}).call(this);
