// Generated by CoffeeScript 1.3.3
(function() {
  var ITunesLib, fs, ituneslib, moment, plist,
    __hasProp = {}.hasOwnProperty;

  fs = require('fs');

  plist = require('plist');

  moment = require('moment');

  module.exports = ituneslib = function(options) {
    var itunesLib;
    if (options == null) {
      options = {};
    }
    return itunesLib = module.exports.instance = new ITunesLib(options);
  };

  ITunesLib = (function() {

    function ITunesLib(filepath) {
      this.data = plist.parseFileSync(filepath);
      this.tracks = this.data["Tracks"];
    }

    ITunesLib.prototype.size = function() {
      return Object.keys(this.tracks).length;
    };

    ITunesLib.prototype.songs = function() {
      var track, trackid, _ref, _results;
      _ref = this.tracks;
      _results = [];
      for (trackid in _ref) {
        if (!__hasProp.call(_ref, trackid)) continue;
        track = _ref[trackid];
        _results.push({
          title: track["Name"],
          artist: track["Artist"],
          album: track["Album"],
          play_count: track["Play Count"],
          date_added: moment(track["Date Added"]).toDate(),
          play_date: moment(track["Play Date UTC"]).toDate()
        });
      }
      return _results;
    };

    return ITunesLib;

  })();

}).call(this);
